# Generated by Django 5.0 on 2023-12-21 02:37

from django.db import migrations
from django.contrib.auth import get_user_model


def create_initial_superuser(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@email.com', 'adminadmin')


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(create_initial_superuser),
    ]

